prism_host: ahncloudprism.tfoundry.com
ejabberd_host: ahncloudim.tfoundry.com
ejabberd_secret: adhearsionr0x!
postgres_db: 'postgres://ahncloud:ahnr0x@ahncloudprism.tfoundry.com/ahncloud'
rayo_routing_dir: /opt/voxeo/prism/apps/rayo/WEB-INF/classes/
api_matrix:
  login_uri: https://auth.tfoundry.com/oauth/authorize?client_id=%s&client_secret=%s&response_type=code&scope=profile&redirect_uri=%s
  auth_uri: https://auth.tfoundry.com/me.json?access_token=%s
  redirect_uri: http://ahncloudprism.tfoundry.com/oauth/callback
  client_id: 29fac5a3b2bfafbcd32b0e472ccfd5fe 
  client_secret: f668376016ec639a 
flash_notice:
  log_in: You are now signed in. Welcome %s!
  log_out: You have logged out.
  app_created: Successfully created App %s
  app_deleted: App successfully deleted.
  did_assigned: DID %s assigned to App %s
  name_updated: Name updated for App %s
flash_error:
  auth_failed: Failed to authenticate user.
  app_not_found: App not found.
  did_assign_failed: We are out of DID's. Assignment to %s failed. Please try again later.
rayo:
  add_app: http://%s:8080/rayo/jmx/exec/com.rayo.gateway:Type=Admin,name=Admin/registerApplication/staging/%s/%s
  add_sip: http://%s:8080/rayo/jmx/exec/com.rayo.gateway:Type=Admin,name=Admin/registerAddress/%s/%s
  remove_app: http://%s:8080/rayo/jmx/exec/com.rayo.gateway:Type=Admin,name=Admin/unregisterApplication/%s

